# Generated by Django 3.2.16 on 2024-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=140, verbose_name='Текст комментария'),
        ),
    ]
